language: python

python:
  - "2.7.13"

before_install:
  - export TZ=Europe/Brussels
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda install --yes numpy scipy
  - pip install --quiet pytest pytest-cov pytest-xdist

install:
  - travis_wait 40 python setup.py install --quiet
  # Install and compile libsvm and liblinear  
  - sudo apt-get install -y build-essential
  - git clone https://github.com/cjlin1/libsvm
  - cd libsvm; make lib; sudo cp libsvm.so.2 /lib; sudo ln -s /lib/libsvm.so.2 /lib/libsvm.so; cd ..
  - git clone https://github.com/cjlin1/liblinear
  - cd liblinear; make lib; sudo cp liblinear.so.3 /lib; sudo ln -s /lib/liblinear.so.3 /lib/liblinear.so; cd ..  

script:
  - pytest --cov=pattern
